version: "3.8"
services:
    acceptance-testing-boot-environment:
        build:
            context: ./acceptance-testing-boot-environment
        ports:
            - "3002:3001"
    platform-manifest-collation-system:
        build:
            context: ./platform-manifest-collation-system
        ports:
            - "3001:3001"       
    aca:
      build:
          context: ./hirs-aca
      container_name: hirs-aca
      ports:
         - "8443:8443"
      entrypoint: ["/bin/bash","-c"]
      command: [/root/setup_aca.sh]
      hostname: hirs-aca
    nginx:
        restart: always
        build:
            context: ./nginx-proxy
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - "aca"
            - "acceptance-testing-boot-environment"
            - "platform-manifest-collation-system"
        volumes:
            - ./nginx-proxy/certs:/etc/nginx/certs